// Exact column ordering captured from the customer-supplied template:
//   .private/template.xlsx
// Header strings reproduce the template verbatim (including the
// "Vendor Name | (on the invoice)" pipe). Trailing empty columns on CM
// are preserved so column counts match the template exactly.

export const CLIENT_INFO_HEADERS = [
  "Client Name",
  "Client Status",
  "Order / Period",
  "Order Start Date",
  "Order Deadline",
  "Link Volume",
  "Budget Per Target",
  "Min. DR",
  "Min. Traffic",
  "Order Payment Date",
  "Order Type",
  "Domains",
  "Target Pages",
  "Domain Approval",
  "Domain Approval Tracker",
  "Order / Period Notes",
  "Team in Charge",
  "Links Live",
  "Order / Period Shortfall",
  "Link Tracker",
  "Order Status",
  "Account Manager",
] as const;

export const CM_HEADERS = [
  "Period",
  "Period Start Date",
  "Order #",
  "Order Date",
  "Placement Domain",
  "Placement URL",
  "DR",
  "Traffic",
  "Order Price",
  "DB Price",
  "Can Use",
  "TAT",
  "Target URL",
  "Anchor Text",
  "Link Type",
  "Budget",
  "Profit",
  "Status",
  "Publishing Date",
  "Contact Email",
  "Thread ID",
  "Team",
  "Notes",
  "Review Status",
  "Review Notes",
  "Topics/Snippets",
  "GP Doc",
  "Content Status",
  "Payment Invoice",
  "Vendor Name | (on the invoice)",
  "Request Type",
  "Invoice Link No.",
  "Payment Status",
  "Payment Notes",
  "",
  "",
  "",
  "",
  "Hash",
] as const;

export const CM_HISTORY_HEADERS = [
  "Order #",
  "SnapshotId",
  "SnapshotType",
  "CapturedAt",
  "CapturedBy",
  "RowIndex",
  "Fingerprint",
  "Strong_ContactEmail",
  "Strong_AnchorText",
  "Strong_OrderPrice",
  "Strong_Status",
  "Strong_ThreadID",
  "Payload",
] as const;

export const CM_STATE_HEADERS = [
  "Order #",
  "Fingerprint",
  "LastCapturedAt",
  "LastSnapshotId",
  "RowIndex",
  "Strong_ContactEmail",
  "Strong_AnchorText",
  "Strong_OrderPrice",
  "Strong_Status",
  "Strong_ThreadID",
] as const;

export const REFERRING_DOMAINS_HEADERS = [
  "#",
  "Domain",
  "Is spam",
  "DR",
  "Dofollow ref. domains",
  "Dofollow linked domains",
  "Traffic ", // trailing space matches template
  "Keywords ",
  "Links to target",
  "New links",
  "Lost links",
  "Dofollow links",
  "First seen",
  "Lost",
] as const;
